version: '3'
networks:
 campus_virtual:

services:
   ud-repository-stadistics:
     build: .
     container_name: ud-repository-stadistics
     restart: on-failure
     env_file:
        - .env
     ports:
        - "3010:3010"
     networks:
        - campus_virtual          

networks:
  campus_virtual:
    external: true
